/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DistrictsRouteImport } from './routes/districts'
import { Route as LocalitiesRouteImport } from './routes/localities'
import { Route as MapRouteImport } from './routes/map'
import { Route as MethodRouteImport } from './routes/method'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as RisksRouteImport } from './routes/risks'
import { Route as RoiRouteImport } from './routes/roi'
import { Route as SegmentsRouteImport } from './routes/segments'
import { Route as DistrictsIdRouteImport } from './routes/districts.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictsRoute = DistrictsRouteImport.update({
  id: '/districts',
  path: '/districts',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalitiesRoute = LocalitiesRouteImport.update({
  id: '/localities',
  path: '/localities',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksRoute = RisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => rootRouteImport,
} as any)
const RoiRoute = RoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentsRoute = SegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictsIdRoute = DistrictsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DistrictsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/districts': typeof DistrictsRouteWithChildren
  '/localities': typeof LocalitiesRoute
  '/map': typeof MapRoute
  '/method': typeof MethodRoute
  '/plan': typeof PlanRoute
  '/playbook': typeof PlaybookRoute
  '/risks': typeof RisksRoute
  '/roi': typeof RoiRoute
  '/segments': typeof SegmentsRoute
  '/districts/$id': typeof DistrictsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/districts': typeof DistrictsRouteWithChildren
  '/localities': typeof LocalitiesRoute
  '/map': typeof MapRoute
  '/method': typeof MethodRoute
  '/plan': typeof PlanRoute
  '/playbook': typeof PlaybookRoute
  '/risks': typeof RisksRoute
  '/roi': typeof RoiRoute
  '/segments': typeof SegmentsRoute
  '/districts/$id': typeof DistrictsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/districts': typeof DistrictsRouteWithChildren
  '/localities': typeof LocalitiesRoute
  '/map': typeof MapRoute
  '/method': typeof MethodRoute
  '/plan': typeof PlanRoute
  '/playbook': typeof PlaybookRoute
  '/risks': typeof RisksRoute
  '/roi': typeof RoiRoute
  '/segments': typeof SegmentsRoute
  '/districts/$id': typeof DistrictsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/districts'
    | '/localities'
    | '/map'
    | '/method'
    | '/plan'
    | '/playbook'
    | '/risks'
    | '/roi'
    | '/segments'
    | '/districts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/districts'
    | '/localities'
    | '/map'
    | '/method'
    | '/plan'
    | '/playbook'
    | '/risks'
    | '/roi'
    | '/segments'
    | '/districts/$id'
  id:
    | '__root__'
    | '/'
    | '/districts'
    | '/localities'
    | '/map'
    | '/method'
    | '/plan'
    | '/playbook'
    | '/risks'
    | '/roi'
    | '/segments'
    | '/districts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DistrictsRoute: typeof DistrictsRouteWithChildren
  LocalitiesRoute: typeof LocalitiesRoute
  MapRoute: typeof MapRoute
  MethodRoute: typeof MethodRoute
  PlanRoute: typeof PlanRoute
  PlaybookRoute: typeof PlaybookRoute
  RisksRoute: typeof RisksRoute
  RoiRoute: typeof RoiRoute
  SegmentsRoute: typeof SegmentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/districts': {
      id: '/districts'
      path: '/districts'
      fullPath: '/districts'
      preLoaderRoute: typeof DistrictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localities': {
      id: '/localities'
      path: '/localities'
      fullPath: '/localities'
      preLoaderRoute: typeof LocalitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks': {
      id: '/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof RisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roi': {
      id: '/roi'
      path: '/roi'
      fullPath: '/roi'
      preLoaderRoute: typeof RoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segments': {
      id: '/segments'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof SegmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/districts/$id': {
      id: '/districts/$id'
      path: '/$id'
      fullPath: '/districts/$id'
      preLoaderRoute: typeof DistrictsIdRouteImport
      parentRoute: typeof DistrictsRoute
    }
  }
}

interface DistrictsRouteChildren {
  DistrictsIdRoute: typeof DistrictsIdRoute
}

const DistrictsRouteChildren: DistrictsRouteChildren = {
  DistrictsIdRoute: DistrictsIdRoute,
}

const DistrictsRouteWithChildren = DistrictsRoute._addFileChildren(
  DistrictsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DistrictsRoute: DistrictsRouteWithChildren,
  LocalitiesRoute: LocalitiesRoute,
  MapRoute: MapRoute,
  MethodRoute: MethodRoute,
  PlanRoute: PlanRoute,
  PlaybookRoute: PlaybookRoute,
  RisksRoute: RisksRoute,
  RoiRoute: RoiRoute,
  SegmentsRoute: SegmentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
